# Generated by Django 4.1 on 2022-10-06 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(max_length=20, null=True)),
                ('firstName', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=80, null=True)),
                ('email', models.CharField(max_length=30, null=True)),
                ('jobTitle', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegNo', models.CharField(max_length=10, null=True)),
                ('type', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('capacity', models.CharField(max_length=10, null=True)),
                ('charges', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('available', 'available'), ('booked', 'booked')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('phone', models.CharField(max_length=13, null=True)),
                ('address', models.CharField(max_length=80, null=True)),
                ('email', models.CharField(max_length=30, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Book_Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegNo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hama.vehicle')),
            ],
        ),
    ]
